### ISSUE TITLE
How to run both Junit5 and TestNG tests with testng-engine?

### ISSUE THREAD

**Issue by scripnichenko** [junit-team/testng-engine#10]
**GIVEN** 200+ TestNG REST API tests in a separate repository
**WHEN** I add TestNG tests to an existing maven spring-boot project with Junit5 tests
**AND** I have maven dependencies` junit-jupiter v5.7.1` , `testng  v7.4.0`, `testng-engine v1.0.0-RC1`
**AND** `maven-surefire-plugin v3.0.0-M4` to execute tests
**AND** I run `mvn test`
**THEN**   

- **Expected**: all tests executed (TestNG + Junit5)
- **Actual**: only TestNG tests are exectued.

I am thinking this is a `maven-surefire-plugin `set-up issue:

_Chapter **You can run TestNG tests combined with JUnit5 tests.**_
https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html

Team, can I ask for suggestions how set-up should be looks like?

**Comment by marcphilipp** [comment]
@scripnichenko Could you please upgrade to Surefire 3.0.0-M5. IIRC there was a change in how it determines which test framework to use for execution. Alternatively, you can [force it](https://maven.apache.org/surefire/maven-surefire-plugin/examples/providers.html) to use the `surefire-junit-platform` provider.

**Comment by scripnichenko** [comment]
@marcphilipp  you are right! 🥇 
Updating dependency to `maven-surefire-plugin v3.0.0-M5`  allows starting both tests (even without _force_ option)
