### ISSUE TITLE
Update to TestNG 7.10.0 fails

### ISSUE THREAD

**Issue by sormuras** [junit-team/testng-engine#116]
As noted in
- https://github.com/junit-team/junit5-samples/pull/381#issuecomment-2042502044
the method `long[] getInstanceHashCodes()` was removed from `testng-core-api/src/main/java/org/testng/IClass.java`.

That method is used by the `testng-engine` implementation here:
- https://github.com/junit-team/testng-engine/blob/75c75ea9405d59b2227c9d6401749d9a7592a87a/src/main/java/org/junit/support/testng/engine/TestDescriptorFactory.java#L71

**Comment by krmahadevan** [comment]
@sormuras - This is now fixed as part of fixing https://github.com/testng-team/testng/issues/3110

Once i get a confirmation from the user who logged the above mentioned issue, I will wrap up the release.

**Comment by marcphilipp** [comment]
@krmahadevan Thanks for the quick turnaround! 👍

**Comment by marcphilipp** [comment]
@krmahadevan Is there a replacement for the deprecated API that should be used instead?

**Comment by krmahadevan** [comment]
TestNG `7.10.1` is now available on Maven central https://repo1.maven.org/maven2/org/testng/testng/7.10.1/

**Comment by krmahadevan** [comment]
> @krmahadevan Is there a replacement for the deprecated API that should be used instead?

No. That api was not serving any purpose from an end user perspective, because all it was doing was giving out hashCodes of the test class objects that were produced by each of the factory call invocations. That was why we moved all of them out from the public facing to internal, because they are still needed internal. I need to still sift through the codebase to see if they are still needed internally or not. It's like peeling onions :)

**Comment by marcphilipp** [comment]
Ok, so do you think it's fine if we keep using it here?

**Comment by krmahadevan** [comment]
It will be removed in the upcoming versions @marcphilipp 

The TestNG codebase uses the same api but from an internal package. So it's needed internally, but it wont be available for TestNG consumers.

**Comment by marcphilipp** [comment]
We use it to compute the test class instance index which is appended to the display name:
https://github.com/junit-team/testng-engine/blob/5d5e0e71c0b943173459e734c47935a5de04ef32/src/main/java/org/junit/support/testng/engine/TestDescriptorFactory.java#L70-L82

This is important to be able to differentiate between the different parameterized executions. Is there an undeprecated API that we can use to achieve the same?

**Comment by marcphilipp** [comment]
> TestNG `7.10.1` is now available on Maven central [repo1.maven.org/maven2/org/testng/testng/7.10.1](https://repo1.maven.org/maven2/org/testng/testng/7.10.1/)

Could you please also publishing a new 7.11.0-SNAPSHOT to oss.sonatype.org?

**Comment by krmahadevan** [comment]
> We use it to compute the test class instance index which is appended to the display name:
> 
> https://github.com/junit-team/testng-engine/blob/5d5e0e71c0b943173459e734c47935a5de04ef32/src/main/java/org/junit/support/testng/engine/TestDescriptorFactory.java#L70-L82
> 
> This is important to be able to differentiate between the different parameterized executions. Is there an undeprecated API that we can use to achieve the same?

Ok. I will have to find out. Can this wait? If possible please log a bug so that I don't forget. Right now in the middle of an assignment that I need to wrap up within this week as part of an interview process. 

Would want to first get that out of the way

**Comment by krmahadevan** [comment]
> > TestNG `7.10.1` is now available on Maven central [repo1.maven.org/maven2/org/testng/testng/7.10.1](https://repo1.maven.org/maven2/org/testng/testng/7.10.1/)
> 
> Could you please also publishing a new 7.11.0-SNAPSHOT to oss.sonatype.org?

Sure. I will do that in sometime.

**Comment by marcphilipp** [comment]
> Ok. I will have to find out. Can this wait? If possible please log a bug so that I don't forget. Right now in the middle of an assignment that I need to wrap up within this week as part of an interview process.
> 
> Would want to first get that out of the way

Sure, no worries! I created https://github.com/testng-team/testng/issues/3111

> > Could you please also publishing a new 7.11.0-SNAPSHOT to oss.sonatype.org?
> 
> Sure. I will do that in sometime.

I'll leave this issue open until that is done because I've configured the build to ignore the failing tests against the snapshot version for now which I'd like to revert: https://github.com/junit-team/testng-engine/blob/ef0bb1be929b4472083dbbb9382505e52bfc7fd0/build.gradle.kts#L212

**Comment by krmahadevan** [comment]
@marcphilipp - The next snapshot has been published https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/7.11.0-SNAPSHOT/
