### ISSUE TITLE
Document that the `testng.version` system property must be set to execute tests in IDE

### ISSUE THREAD

**Issue by sbrannen** [junit-team/testng-engine#15]
## Overview

An external contributor wishing to execute tests in the IDE encounters the following stack trace.

```
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because "version" is null
	at org.apache.maven.artifact.versioning.ComparableVersion.parseVersion(ComparableVersion.java:599)
	at org.apache.maven.artifact.versioning.ComparableVersion.<init>(ComparableVersion.java:589)
	at org.junit.support.testng.engine.TestContext.testNGVersion(TestContext.java:18)
```

Only after some digging, does one realize that they have to set the `testng.version` system property in order to execute tests in IDE.

This is required for each test class that one wants to execute.

## Deliverables

- [ ] Document that the `testng.version` system property must be set to execute tests in IDE.
- [ ] Consider an alternative approach to executing tests within an IDE and document that.

**Comment by sbrannen** [comment]
>  Consider an alternative approach to executing tests within an IDE and document that.

@marcphilipp, have you considered using the latest TestNG version as the default if that system property isn't set?

How are you actually running tests in your IDE?

**Comment by marcphilipp** [comment]
> How are you actually running tests in your IDE?

I'm always running them via Gradle, even from IntelliJ IDEA.

> have you considered using the latest TestNG version as the default if that system property isn't set?

We can certainly do that.
