### ISSUE TITLE
Engine not im BOM?

### ISSUE THREAD

**Issue by realdadfish** [junit-team/testng-engine#23]
Hi!

This library is not listed in the most recent BOM (https://repo1.maven.org/maven2/org/junit/junit-bom/5.9.2/junit-bom-5.9.2.pom) - why? Is there a different BOM in which this library is part of or is there a general rule that support libraries are kept out of the main BOM?

Thanks!

**Comment by marcphilipp** [comment]
This engine's release cycle is completely independent of JUnit 5 and therefore not included in the latter's BOM.

As documented in the readme, it requires at least JUnit Platform 1.5.x but should work with any later version.

**Comment by realdadfish** [comment]
OK, understood, I was under the impression that the JUnit BOM is also used to list compatible artifacts even when developed independently, in the junit realm. Thanks for clearing that up.
